# deault field list
well_field_list = [
    "idpozo",
    "area", "cod_area",
    "sigla",
    "empresa",
    "yacimiento", "cod_yacimiento",
    "tipo_recurso", "sub_tipo_recurso",
    "provincia",
    "cota", "profundidad",
    "geojson", "geom",
    "cuenca", "gasplus",
    "tipopozo",
    "tipoestado", "tipoextraccion",
    "clasificacion", "subclasificacion",
    "formacion",
    "adjiv_fecha_inicio_perf", "adjiv_fecha_fin_perf",
    "adjiv_fecha_inicio_term", "adjiv_fecha_fin_term",

]

production_field_list = [
    'idpozo',
    'idempresa',
    'empresa',
    'sigla',
    'anio',
    'mes',
    'prod_pet',
    'prod_gas',
    'prod_agua',
    'iny_agua',
    'iny_gas',
    'iny_co2',
    'iny_otro',
    'tef',
    'vida_util',
    'tipoextraccion',
    'tipoestado',
    'tipopozo',
    'formprod',
    'idareapermisoconcesion',
    'areapermisoconcesion',
    'idareayacimiento',
    'areayacimiento',
    'cuenca',
    'provincia',
    'coordenadax',
    'coordenaday',
    'profundidad',
    'formacion',
    'tipo_de_recurso',
    'proyecto',
    'clasificacion',
    'subclasificacion',
    'sub_tipo_recurso',
    'fecha_data',
    'fechaingreso',
    'rectificado',
    'habilitado',
    'idusuario',
    'observaciones',
]
